web/epaper/urls.py
from django.urls import path


from . import views

urlpatterns = [
    path('epaper/',views.EPaperViews.as_view(),name='epaper'),
    path('thanks/',views.EPaperThanksView.as_view(),name='thanks'),
]

web/main/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('products/',include(('products.urls','products'),namespace='products')),
    path('epaper/',include(('epaper.urls','epaper'),namespace='epaper')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/products/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('list/', views.ProductListView.as_view(), name='list'),
    path('<int:pk>/', views.ProductDetailView.as_view(), name='detail')
]

web/products/models.py
from django.db import models
# Create your models here.
from django.utils.translation import gettext_lazy as _ 
from core.helpers import upload_handle
from django.utils.translation import get_language

class Product(models.Model):
    '''
    商品模型
    '''
    name = models.CharField(_('Product Name'), max_length=50)
    description = models.TextField(_('Product Description'), max_length=500, null=True, blank=True)
    price = models.PositiveIntegerField(_('Product Price'), default=0)
    created = models.DateTimeField(_('Created Date'), auto_now_add=True)
    modified = models.DateTimeField(_('Modified Date'), auto_now=True)
    category = models.ForeignKey(
        'products.ProductCategory', blank=True, null=True, 
        on_delete=models.RESTRICT, verbose_name=_('Product Category'), related_name='product_set'
    )

    class Meta:
        verbose_name = _('Product')
        verbose_name_plural = _('Product')
        ordering = ['-created']

    def __str__(self):
        return f'{self.name}'
    
class ProductCategory(models.Model):
    name = models.CharField('商品分類名稱',max_length=50)
    name_en = models.CharField('商品分類名稱(英)', max_length=50, null=True, blank=True) 
    description = models.TextField('商品分類描述',max_length=500,null=True,blank=True)
    description_en = models.TextField('商品分類描述(英)', max_length=500, null=True, blank=True) # new
    created = models.DateTimeField('建立日期',auto_now_add=True)
    modified = models.DateTimeField('修改日期',auto_now=True)
    image =models.ImageField('圖片',null=True,blank=True ,upload_to=upload_handle)

    @property
    def name_locale(self):
        language = get_language()
        if language== 'zh-hant':
            return f'{self.name}'
        elif language == 'en':
            return f'{self.name_en}'
        return f"{self.name}"

    @property
    def description_locale(self):
        language = get_language()
        if language== 'zh-hant':
            return f'{self.description}'
        elif language == 'en':
            return f'{self.description_en}'
        return f"{self.description}"
    
    class Meta:
        verbose_name='商品分類'
        verbose_name_plural='商品分類'
        ordering=['-created']    
        
    def __str__(self) -> str:
        return f'{self.name}'

class ProductImage(models.Model):
    name = models.CharField('商品圖片說明',max_length=50)
    product = models.ForeignKey('products.Product',on_delete=models.CASCADE,related_name='product_image_set')
    image = models.ImageField('圖片',null=True,blank=True,upload_to=upload_handle)
    order = models.PositiveBigIntegerField(null=True,blank=True)
    class Meta:
        verbose_name= '商品圖片'
        verbose_name_plural='商品圖片'
        ordering=['order']
    def __str__(self) -> str:
        return f'{self.name}'

web/products/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,ListView,DetailView
from products.models import Product,ProductCategory
# Create your views here.


class HomeView(TemplateView):
    template_name = 'products/home.html'
    
    def get(self,request,*args, **kwargs):
        products = Product.objects.all()
        left_product_categories= ProductCategory.objects.all()[0:2]
        right_product_categories= ProductCategory.objects.all()[2:3]
        right_product_category=right_product_categories.first() if right_product_categories else None
        
        context = self.get_context_data(**kwargs)
        context['items']= products
        context['left_product_categories'] = left_product_categories
        context['right_product_category'] = right_product_category
        return self.render_to_response(context)
    
class ProductListView(ListView):
    model= Product
    template_name = 'products/list.html'
    context_object_name = 'items'
    paginate_by=10
    
class ProductDetailView(DetailView):
    model = Product
    template_name ='products/detail/template1.html'
    context_object_name ='item'

web/products/templates/products/base.html
<!-- products/templates/products/base.html -->
{% load static %}
{% load i18n %}
{% load core_tag %}
{% get_current_language as LANGUAGE_CODE %}
{% get_setting LANGUAGE_CODE as get_setting %}
{% get_setting_list as get_setting_list %}
<!DOCTYPE html>

<html lang="zh-hant">
<head>
<text id="sitename">
    <tspan x="108.94" y="325">{{ get_setting.sitename }}</tspan>
</text>
<ul class="social-media">
    <li>
        <a href="{{ get_setting.facebook }}" target="_blank">
            <i class="tf-ion-social-facebook"></i>
        </a>
    </li>
    <li>
        <a href="{{ get_setting.instagram }}" target="_blank">
            <i class="tf-ion-social-instagram"></i>
        </a>
    </li>
    <li>
        <a href="{{ get_setting.twitter }}" target="_blank">
            <i class="tf-ion-social-twitter"></i>
        </a>
    </li>
</ul>
<!-- Basic Page Needs
================================================== -->
<meta charset="utf-8">
<title>IvanKao | E-commerce </title>

<!-- Mobile Specific Metas
================================================== -->
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="Construction Html5 Template">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0">
<meta name="author" content="Themefisher">
<meta name="generator" content="Themefisher Constra HTML Template v1.0">

<!-- Favicon -->
<link rel="shortcut icon" type="image/x-icon" href="{% get_media_prefix %}{{ get_setting.favicon }}">
<!-- Themefisher Icon font -->
<link rel="stylesheet" href="{% static 'products/plugins/themefisher-font/style.css' %}">
<!-- bootstrap.min css -->
<link rel="stylesheet" href="{% static 'products/plugins/bootstrap/css/bootstrap.min.css' %}">

<!-- Animate css -->
<link rel="stylesheet" href="{% static 'products/plugins/animate/animate.css' %}">
<!-- Slick Carousel -->
<link rel="stylesheet" href="{% static 'products/plugins/slick/slick.css' %}">
<link rel="stylesheet" href="{% static 'products/plugins/slick/slick-theme.css' %}">

<!-- Main Stylesheet -->
<link rel="stylesheet" href="{% static 'products/css/style.css' %}">

</head>

<body id="body">

<!-- Start Top Header Bar -->
<section class="top-header">
    <div class="container">
		<div class="row">
			<div class="col-md-4 col-xs-12 col-sm-4">
                <img style="height: 12em;width: 12em" src="{% get_media_prefix %}{{ get_setting.logo }}">
                <div class="contact-number">
                    <i class="tf-ion-ios-telephone"></i>
                    <span>{{ get_setting.phone }}</span>
					<!-- 訂閱電子報 -->
                    <span><a href="{% url 'epaper:epaper' %}">{% translate 'Subscribe to the newsletter' %}</a></span>
                </div>
            </div>
			<div class="col-md-4 col-xs-12 col-sm-4">
				<!-- Site Logo -->
				<div class="logo text-center">
					<a href="index.html">
						<!-- replace logo here -->
						<svg width="135px" height="29px" viewBox="0 0 155 29" version="1.1" xmlns="http://www.w3.org/2000/svg"
							xmlns:xlink="http://www.w3.org/1999/xlink">
							<g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" font-size="40"
								font-family="AustinBold, Austin" font-weight="bold">
								<g id="Group" transform="translate(-108.000000, -297.000000)" fill="#000000">
									<text id="AVIATO">
										<tspan x="108.94" y="325">AVIATO</tspan>
									</text>
								</g>
							</g>
						</svg>
					</a>
				</div>
			</div>
			<div class="col-md-4 col-xs-12 col-sm-4">
				<!-- Cart -->
				<ul class="top-menu text-right list-inline">
					<li class="dropdown cart-nav dropdown-slide">
						<a href="#!" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"><i
								class="tf-ion-android-cart"></i>Cart</a>
						<div class="dropdown-menu cart-dropdown">
							<!-- Cart Item -->
							<div class="media">
								<a class="pull-left" href="#!">
									<img class="media-object" src="{% static 'products/images/shop/cart/cart-1.jpg'%}" alt="image" />
								</a>
								<div class="media-body">
									<h4 class="media-heading"><a href="#!">Ladies Bag</a></h4>
									<div class="cart-price">
										<span>1 x</span>
										<span>1250.00</span>
									</div>
									<h5><strong>$1200</strong></h5>
								</div>
								<a href="#!" class="remove"><i class="tf-ion-close"></i></a>
							</div><!-- / Cart Item -->
							<!-- Cart Item -->
							<div class="media">
								<a class="pull-left" href="#!">
									<img class="media-object" src="{% static 'products/images/shop/cart/cart-2.jpg'%}" alt="image" />
								</a>
								<div class="media-body">
									<h4 class="media-heading"><a href="#!">Ladies Bag</a></h4>
									<div class="cart-price">
										<span>1 x</span>
										<span>1250.00</span>
									</div>
									<h5><strong>$1200</strong></h5>
								</div>
								<a href="#!" class="remove"><i class="tf-ion-close"></i></a>
							</div><!-- / Cart Item -->

							<div class="cart-summary">
								<span>Total</span>
								<span class="total-price">$1799.00</span>
							</div>
							<ul class="text-center cart-buttons">
								<li><a href="cart.html" class="btn btn-small">View Cart</a></li>
								<li><a href="checkout.html" class="btn btn-small btn-solid-border">Checkout</a></li>
							</ul>
						</div>

					</li><!-- / Cart -->

					<!-- Search -->
					<li class="dropdown search dropdown-slide">
						<a href="#!" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"><i
								class="tf-ion-ios-search-strong"></i> Search</a>
						<ul class="dropdown-menu search-dropdown">
							<li>
								<form action="post"><input type="search" class="form-control" placeholder="Search..."></form>
							</li>
						</ul>
					</li><!-- / Search -->

					<!-- Languages -->
					<li class="commonSelect">
						<form action="{% url 'set_language' %}" method="post">
							{% csrf_token %}
							<input name="next" type="hidden" value="{{ redirect_to }}">
							<select name="language" class="form-control" onchange="this.form.submit()">
								{% for language in get_setting_list %}
									<option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
										{{ language.name_local }} ({{ language.code }})
									</option>
								{% endfor %}
							</select>
						</form>
					</li><!-- / Languages -->

				</ul><!-- / .nav .navbar-nav .navbar-right -->
			</div>
		</div>
	</div>
</section><!-- End Top Header Bar -->

{% block content %}
{% endblock content %}

<footer class="footer section text-center">
    <div class="container">
		<div class="row">
			<div class="col-md-12">
				<ul class="social-media">
					<li>
						<a href="https://www.facebook.com/themefisher">
							<i class="tf-ion-social-facebook"></i>
						</a>
					</li>
					<li>
						<a href="https://www.instagram.com/themefisher">
							<i class="tf-ion-social-instagram"></i>
						</a>
					</li>
					<li>
						<a href="https://www.twitter.com/themefisher">
							<i class="tf-ion-social-twitter"></i>
						</a>
					</li>
					<li>
						<a href="https://www.pinterest.com/themefisher/">
							<i class="tf-ion-social-pinterest"></i>
						</a>
					</li>
				</ul>
				<ul class="footer-menu text-uppercase">
					<li>
						<a href="contact.html">CONTACT</a>
					</li>
					<li>
						<a href="shop.html">SHOP</a>
					</li>
					<li>
						<a href="pricing.html">Pricing</a>
					</li>
					<li>
						<a href="contact.html">PRIVACY POLICY</a>
					</li>
				</ul>
				<p class="copyright-text">Copyright &copy;2021, Designed &amp; Developed by <a href="https://themefisher.com/">Themefisher</a></p>
			</div>
		</div>
	</div>
</footer>

    <!-- 
    Essential Scripts
    =====================================-->
    
    <!-- Main jQuery -->
    <script src="{% static 'products/plugins/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap 3.1 -->
    <script src="{% static 'products/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- Bootstrap Touchpin -->
    <script src="{% static 'products/plugins/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.js' %}"></script>
    <!-- Instagram Feed Js -->
    <script src="{% static 'products/plugins/instafeed/instafeed.min.js' %}"></script>
    <!-- Video Lightbox Plugin -->
    <script src="{% static 'products/plugins/ekko-lightbox/dist/ekko-lightbox.min.js' %}"></script>
    <!-- Count Down Js -->
    <script src="{% static 'products/plugins/syo-timer/build/jquery.syotimer.min.js' %}"></script>

    <!-- slick Carousel -->
    <script src="{% static 'products/plugins/slick/slick.min.js' %}"></script>
    <script src="{% static 'products/plugins/slick/slick-animation.min.js' %}"></script>

    <!-- Google Mapl -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCC72vZw-6tGqFyRhhg5CkF2fqfILn2Tsw"></script>
    <script type="text/javascript" src="{% static 'products/plugins/google-map/gmap.js' %}"></script>

    <!-- Main Js File -->
    <script src="{% static 'products/js/script.js' %}"></script>
    

</body>
</html>

web/products/templates/products/home.html
<!-- products/templates/products/home.html -->
{% extends "products/base.html" %}
{% load static %}

{% block content %}
<section class="product-category section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title text-center">
                    {% if LANGUAGE_CODE == 'zh-hant' %}
                        以商品分類尋找屬於您的商品
                    {% elif LANGUAGE_CODE == 'en' %}
                        Product category
                    {% endif %}
                </div>
            </div>
            <div class="col-md-6">
                <div class="category-box">
                    <a href="#!">
                        {% if get_setting.home_type1.image %}
                            <img src="{% get_media_prefix %}{{ get_setting.home_type1.image }}" alt="" />
                        {% endif %}
                        <div class="content">
                            <h3 style="color: white;">{{ get_setting.home_type1.name }}</h3>
                            <p style="color: white;">{{ get_setting.home_type1.description }}</p>
                        </div>
                    </a>	
                </div>
                <div class="category-box">
                    <a href="#!">
                        {% if get_setting.home_type2.image %}
                            <img src="{% get_media_prefix %}{{ get_setting.home_type2.image }}" alt="" />
                        {% endif %}
                        <div class="content">
                            <h3 style="color: white;">{{ get_setting.home_type2.name }}</h3>
                            <p style="color: white;">{{ get_setting.home_type2.description }}</p>
                        </div>
                    </a>	
                </div>
            </div>
            <div class="col-md-6">
                <div class="category-box category-box-2">
                    <a href="#!">
                        {% if get_setting.home_type3.image %}
                            <img src="{% get_media_prefix %}{{ get_setting.home_type3.image }}" alt="" />
                        {% endif %}
                        <div class="content">
                            <h3 style="color: white;">{{ get_setting.home_type3.name }}</h3>
                            <p style="color: white;">{{ get_setting.home_type3.description }}</p>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="products section bg-gray">
    <div class="container">
        <div class="row">
            <div class="title text-center">
                <h2>所有商品</h2>
            </div>
        </div>
        <div class="row">
            {% for item in items %}
                <div class="col-md-4">
                    <div class="product-item">
                        <div class="product-thumb">
                            {% if item.product_image_set.all.0.image %}
                                <img class="img-responsive" src="{{ item.product_image_set.all.0.image.url }}" alt="product-img" />
                            {% endif %}
                            <div class="preview-meta">
                                <ul>
                                    <li>
                                        <span  data-toggle="modal" data-target="#product-modal-{{ item.id }}">
                                            <i class="tf-ion-ios-search-strong"></i>
                                        </span>
                                    </li>
                                    <li>
                                        <a href="#" ><i class="tf-ion-ios-heart"></i></a>
                                    </li>
                                    <li>
                                        <a href="#!"><i class="tf-ion-android-cart"></i></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="product-content">
                            <h4><a href="product-single.html">{{ item.name }}</a></h4>
                            <p class="price">${{ item.price }}</p>
                        </div>
                    </div>
                </div>
                <!-- Modal -->
                <div class="modal product-modal fade" id="product-modal-{{ item.id }}">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <i class="tf-ion-close"></i>
                    </button>
                    <div class="modal-dialog " role="document">
                        <div class="modal-content">
                            <div class="modal-body">
                                <div class="row">
                                    <div class="col-md-8 col-sm-6 col-xs-12">
                                        <div class="modal-image">
                                            {% if item.product_image_set.all.0.image %}
                                                <img class="img-responsive" src="{{ item.product_image_set.all.0.image.url }}" alt="product-img" />
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="col-md-4 col-sm-6 col-xs-12">
                                        <div class="product-short-details">
                                            <h2 class="product-title">{{ item.name }}</h2>
                                            <p class="product-price">${{ item.price }}</p>
                                            <p class="product-short-description">
                                                {{ item.description }}
                                            </p>
                                            <a href="cart.html" class="btn btn-main">加入購物車</a>
                                            <a href="{% url 'products:detail' item.id %}" class="btn btn-transparent">檢視商品詳細資料</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!-- /.modal -->
            {% endfor %}
        </div>
    </div>
</section>
{% endblock content %}

web/products/templates/products/list.html
<!-- products/templates/products/list.html -->
{% extends "products/base.html" %}
{% load static %}

{% block content %}
<section class="page-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="content">
                    <h1 class="page-name">全部商品</h1>
                    <ol class="breadcrumb">
                        <li><a href="{% url 'products:home' %}">首頁</a></li>
                        <li class="active"><a href="{% url 'products:list' %}">商品列表</a></li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="products section">
    <div class="container">
        <div class="row">
            {% for item in items %}
                <div class="col-md-4">
                    <div class="product-item">
                        <div class="product-thumb">
                            {% if item.product_image_set.all.0.image %}
                                <img class="img-responsive" src="{{ item.product_image_set.all.0.image.url }}" alt="product-img" />
                            {% endif %}
                            <div class="preview-meta">
                                <ul>
                                    <li>
                                        <span  data-toggle="modal" data-target="#product-modal-{{ item.id }}">
                                            <i class="tf-ion-ios-search-strong"></i>
                                        </span>
                                    </li>
                                    <li>
                                        <a href="#" ><i class="tf-ion-ios-heart"></i></a>
                                    </li>
                                    <li>
                                        <a href="#!"><i class="tf-ion-android-cart"></i></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="product-content">
                            <h4><a href="product-single.html">{{ item.name }}</a></h4>
                            <p class="price">${{ item.price }}</p>
                        </div>
                    </div>
                </div>
                <!-- Modal -->
                <div class="modal product-modal fade" id="product-modal-{{ item.id }}">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <i class="tf-ion-close"></i>
                    </button>
                    <div class="modal-dialog " role="document">
                        <div class="modal-content">
                            <div class="modal-body">
                                <div class="row">
                                    <div class="col-md-8 col-sm-6 col-xs-12">
                                        <div class="modal-image">
                                            {% if item.product_image_set.all.0.image %}
                                                <img class="img-responsive" src="{{ item.product_image_set.all.0.image.url }}" alt="product-img" />
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="col-md-4 col-sm-6 col-xs-12">
                                        <div class="product-short-details">
                                            <h2 class="product-title">{{ item.name }}</h2>
                                            <p class="product-price">${{ item.price }}</p>
                                            <p class="product-short-description">
                                                {{ item.description }}
                                            </p>
                                            <a href="cart.html" class="btn btn-main">加入購物車</a>
                                            <a href="{% url 'products:detail' item.id %}" class="btn btn-transparent">檢視商品詳細資料</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!-- /.modal -->
            {% endfor %}
        </div>
    </div>
</section>

{% endblock content %}